# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quiz(object):
    def setupUi(self, quiz):
        quiz.setObjectName("quiz")
        quiz.resize(500, 423)
        quiz.setStyleSheet("background-color: white\n"
"")
        self.label = QtWidgets.QLabel(quiz)
        self.label.setGeometry(QtCore.QRect(20, 60, 121, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.genre = QtWidgets.QComboBox(quiz)
        self.genre.setGeometry(QtCore.QRect(20, 80, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.genre.setFont(font)
        self.genre.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.genre.setObjectName("genre")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.label_2 = QtWidgets.QLabel(quiz)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 161, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.children = QtWidgets.QComboBox(quiz)
        self.children.setGeometry(QtCore.QRect(20, 140, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.children.setFont(font)
        self.children.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.children.setObjectName("children")
        self.children.addItem("")
        self.children.addItem("")
        self.label_3 = QtWidgets.QLabel(quiz)
        self.label_3.setGeometry(QtCore.QRect(230, 120, 261, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.child_age = QtWidgets.QComboBox(quiz)
        self.child_age.setEnabled(False)
        self.child_age.setGeometry(QtCore.QRect(230, 140, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.child_age.setFont(font)
        self.child_age.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.child_age.setObjectName("child_age")
        self.child_age.addItem("")
        self.child_age.addItem("")
        self.child_age.addItem("")
        self.child_age.addItem("")
        self.child_age.addItem("")
        self.label_4 = QtWidgets.QLabel(quiz)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 341, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.last_film = QtWidgets.QLineEdit(quiz)
        self.last_film.setGeometry(QtCore.QRect(20, 200, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.last_film.setFont(font)
        self.last_film.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.last_film.setObjectName("last_film")
        self.label_5 = QtWidgets.QLabel(quiz)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 251, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.duration = QtWidgets.QComboBox(quiz)
        self.duration.setGeometry(QtCore.QRect(20, 260, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.duration.setFont(font)
        self.duration.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.duration.setObjectName("duration")
        self.duration.addItem("")
        self.duration.addItem("")
        self.duration.addItem("")
        self.duration.addItem("")
        self.duration.addItem("")
        self.label_6 = QtWidgets.QLabel(quiz)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 221, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.fav_actor = QtWidgets.QLineEdit(quiz)
        self.fav_actor.setGeometry(QtCore.QRect(20, 320, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.fav_actor.setFont(font)
        self.fav_actor.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.fav_actor.setText("")
        self.fav_actor.setObjectName("fav_actor")
        self.label_7 = QtWidgets.QLabel(quiz)
        self.label_7.setGeometry(QtCore.QRect(20, 360, 231, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.state = QtWidgets.QComboBox(quiz)
        self.state.setGeometry(QtCore.QRect(20, 380, 171, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.state.setFont(font)
        self.state.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.state.setObjectName("state")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.back = QtWidgets.QPushButton(quiz)
        self.back.setGeometry(QtCore.QRect(10, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("border-radius: 20px;\n"
"background-color: white;\n"
"border: 5px solid #0091fa;")
        self.back.setObjectName("back")
        self.next = QtWidgets.QPushButton(quiz)
        self.next.setGeometry(QtCore.QRect(410, 10, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.next.setFont(font)
        self.next.setStyleSheet("border-radius: 20px;\n"
"background-color: white;\n"
"border: 5px solid #0091fa;")
        self.next.setObjectName("next")
        self.search = QtWidgets.QLineEdit(quiz)
        self.search.setGeometry(QtCore.QRect(100, 30, 301, 20))
        self.search.setStyleSheet("background-color: white;\n"
"border: 2px solid #0091fa;")
        self.search.setObjectName("search")
        self.label_8 = QtWidgets.QLabel(quiz)
        self.label_8.setGeometry(QtCore.QRect(100, 10, 221, 16))
        font = QtGui.QFont()
        font.setFamily("hAndy")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(quiz)
        QtCore.QMetaObject.connectSlotsByName(quiz)

    def retranslateUi(self, quiz):
        _translate = QtCore.QCoreApplication.translate
        quiz.setWindowTitle(_translate("quiz", "Подбор фильма"))
        self.label.setText(_translate("quiz", "Выберите жанр"))
        self.genre.setItemText(0, _translate("quiz", "--Не задано--"))
        self.genre.setItemText(1, _translate("quiz", "Комедия"))
        self.genre.setItemText(2, _translate("quiz", "Детектив"))
        self.genre.setItemText(3, _translate("quiz", "Драма"))
        self.genre.setItemText(4, _translate("quiz", "Мелодрама"))
        self.genre.setItemText(5, _translate("quiz", "Документальный"))
        self.genre.setItemText(6, _translate("quiz", "Ужасы"))
        self.genre.setItemText(7, _translate("quiz", "Музыка"))
        self.genre.setItemText(8, _translate("quiz", "Фантастика"))
        self.genre.setItemText(9, _translate("quiz", "Биография"))
        self.genre.setItemText(10, _translate("quiz", "Боевик"))
        self.genre.setItemText(11, _translate("quiz", "Приключения"))
        self.genre.setItemText(12, _translate("quiz", "Война"))
        self.genre.setItemText(13, _translate("quiz", "Семейный"))
        self.genre.setItemText(14, _translate("quiz", "Триллер"))
        self.genre.setItemText(15, _translate("quiz", "Фэнтези"))
        self.genre.setItemText(16, _translate("quiz", "Вестерн"))
        self.genre.setItemText(17, _translate("quiz", "Мистика"))
        self.genre.setItemText(18, _translate("quiz", "Короткометражный"))
        self.genre.setItemText(19, _translate("quiz", "Мюзикл"))
        self.genre.setItemText(20, _translate("quiz", "Исторический"))
        self.genre.setItemText(21, _translate("quiz", "Нуар"))
        self.label_2.setText(_translate("quiz", "Вы идете с детьми?"))
        self.children.setItemText(0, _translate("quiz", "Нет"))
        self.children.setItemText(1, _translate("quiz", "Да"))
        self.label_3.setText(_translate("quiz", "Выберите возраст младшего ребенка"))
        self.child_age.setItemText(0, _translate("quiz", "--Не задано--"))
        self.child_age.setItemText(1, _translate("quiz", "0-5"))
        self.child_age.setItemText(2, _translate("quiz", "6-11"))
        self.child_age.setItemText(3, _translate("quiz", "12-15"))
        self.child_age.setItemText(4, _translate("quiz", "16-17"))
        self.label_4.setText(_translate("quiz", "Какой фильм, из просмотренных недавно, Вам понравился?"))
        self.label_5.setText(_translate("quiz", "Выберите продолжительность"))
        self.duration.setItemText(0, _translate("quiz", "--Не задано--"))
        self.duration.setItemText(1, _translate("quiz", "< 1 часа"))
        self.duration.setItemText(2, _translate("quiz", "1-1.5 часа"))
        self.duration.setItemText(3, _translate("quiz", "1.5-2 часа"))
        self.duration.setItemText(4, _translate("quiz", "> 2 часов"))
        self.label_6.setText(_translate("quiz", "Какой актер Вам нравится?"))
        self.label_7.setText(_translate("quiz", "Выберите район проживания"))
        self.state.setItemText(0, _translate("quiz", "--Не задано--"))
        self.state.setItemText(1, _translate("quiz", "Октябрьский"))
        self.state.setItemText(2, _translate("quiz", "Промышленный"))
        self.state.setItemText(3, _translate("quiz", "Совесткий"))
        self.state.setItemText(4, _translate("quiz", "Ленинский"))
        self.state.setItemText(5, _translate("quiz", "Кировский"))
        self.state.setItemText(6, _translate("quiz", "Куйбышевский"))
        self.state.setItemText(7, _translate("quiz", "Самарский"))
        self.state.setItemText(8, _translate("quiz", "Железнодорожный"))
        self.state.setItemText(9, _translate("quiz", "Красноглинский"))
        self.back.setText(_translate("quiz", "Назад"))
        self.next.setText(_translate("quiz", "Дальше"))
        self.label_8.setText(_translate("quiz", "Поиск по названию фильма"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quiz = QtWidgets.QWidget()
    ui = Ui_quiz()
    ui.setupUi(quiz)
    quiz.show()
    sys.exit(app.exec_())
